# Fetching latest version of Java
FROM openjdk:17
 
# Setting up work directory
WORKDIR /app

# Copy the jar file into our app
COPY ./target/FLotte-1.0-SNAPSHOT.jar /app/FLotte-1.0-SNAPSHOT.jar

# Créez le manifeste
RUN echo "Manifest-Version: 1.0" > MANIFEST.MF
RUN echo "Main-Class: com.flotte.App" >> MANIFEST.MF

# Ajoutez le manifeste au fichier JAR
RUN jar cmf MANIFEST.MF target/FLotte-1.0-SNAPSHOT.jar
RUN jar umf MANIFEST.MF target/FLotte-1.0-SNAPSHOT.jar

# Exposing port 8080
EXPOSE 8080

# Starting the application
CMD ["java", "-jar", "FLotte-1.0-SNAPSHOT.jar"]

# jar cfe ./target/FLotte-1.0-SNAPSHOT.jar com.flotte.App -C target .
# docker run -p 8080:8080 --name flottecontainer flotte
